import type { Software } from './types';

export const SOFTWARE_LIST: Software[] = [
  { id:'1', name:'CCleaner', slug:'ccleaner', version:'6.28.11245', size:'28.5 MB', platform:['windows','mac'], category:'system', description:'世界知名的系统清理优化工具，清除垃圾文件、修复注册表、管理启动项，让电脑运行如飞。', longDescription:'CCleaner 由 Piriform 公司开发，已被 Avast 收购。它可以清理 Windows 系统中的临时文件、浏览器缓存、Cookie、回收站文件、日志文件等，同时提供注册表清理、启动项管理、软件卸载等实用功能。专业版还提供自动清理、实时监控、驱动更新等高级功能。支持 Windows 和 macOS 双平台。', icon:'🧹', screenshots:[], downloadUrl:'https://download.ccleaner.com/ccsetup628.exe', officialSite:'https://www.ccleaner.com', license:'免费/专业版付费', language:['简体中文','繁体中文','English'], updateDate:'2026-06-10', downloads:2850000, rating:4.7, tags:['系统清理','优化','注册表','隐私保护'] },
  { id:'2', name:'Visual Studio Code', slug:'vscode', version:'1.95.3', size:'98.2 MB', platform:['windows','mac','linux'], category:'dev', description:'微软推出的免费开源代码编辑器，支持海量插件，前端后端开发首选。', longDescription:'Visual Studio Code 是微软开发的免费开源代码编辑器，基于 Electron 构建。支持语法高亮、智能代码补全、Git 集成、调试功能。拥有庞大的插件生态系统，支持几乎所有编程语言。内置终端、多光标编辑、代码片段、主题定制等功能。是 Stack Overflow 调查中最受欢迎的开发者工具。', icon:'📝', screenshots:[], downloadUrl:'https://code.visualstudio.com/sha/download?build=stable&os=win32-x64', officialSite:'https://code.visualstudio.com', license:'免费开源 (MIT)', language:['简体中文','English'], updateDate:'2026-06-12', downloads:8900000, rating:4.9, tags:['代码编辑器','IDE','开发工具','开源'] },
  { id:'3', name:'7-Zip', slug:'7zip', version:'24.08', size:'1.6 MB', platform:['windows'], category:'system', description:'开源免费的压缩解压工具，支持 7z/ZIP/RAR/ISO 等 30+ 格式，压缩率极高。', longDescription:'7-Zip 是一款完全免费的开源压缩软件，由 Igor Pavlov 开发。采用 LZMA/LZMA2 压缩算法，7z 格式的压缩率比普通 ZIP 高出 30-70%。支持解压 7z、ZIP、RAR、CAB、ISO、ARJ、LZH、TAR、GZ、BZ2 等 30 多种格式。集成到 Windows 右键菜单，操作简便。唯一的缺点是没有 macOS 版本。', icon:'📦', screenshots:[], downloadUrl:'https://www.7-zip.org/a/7z2408-x64.exe', officialSite:'https://www.7-zip.org', license:'免费开源 (LGPL)', language:['简体中文','English'], updateDate:'2026-05-20', downloads:5600000, rating:4.8, tags:['压缩','解压','文件管理','开源'] },
  { id:'4', name:'火绒安全', slug:'huorong', version:'6.0.2.5', size:'22.1 MB', platform:['windows'], category:'security', description:'国产轻量级安全软件，无广告无捆绑，弹窗拦截功能深受好评。', longDescription:'火绒安全软件是国产安全软件中的一股清流——没有广告、没有捆绑、没有弹窗推广。提供病毒查杀、实时防护、网络防火墙、弹窗拦截、启动项管理、漏洞修复等功能。资源占用极低，适合配置较低的电脑。弹窗拦截功能可以自动拦截各种软件的广告弹窗，被用户称为"良心软件"。', icon:'🛡️', screenshots:[], downloadUrl:'https://down5.huorong.cn/sysdiag-all-6.0.2.5.exe', officialSite:'https://www.huorong.cn', license:'免费', language:['简体中文'], updateDate:'2026-06-08', downloads:1200000, rating:4.6, tags:['杀毒','安全','弹窗拦截','防火墙'] },
  { id:'5', name:'WPS Office', slug:'wps', version:'12.8.0.18906', size:'256 MB', platform:['windows','mac','android','ios'], category:'office', description:'国产办公套件，完美兼容 Word/Excel/PPT 格式，个人版免费使用。', longDescription:'WPS Office 是金山办公旗下的办公软件套件，包含文字（Word）、表格（Excel）、演示（PPT）和 PDF 四大组件。个人版免费使用，无广告。完美兼容 Microsoft Office 格式，支持云同步、多人协作、模板库、AI 写作助手等功能。Android 和 iOS 版本在移动端办公领域占据绝对优势。', icon:'📊', screenshots:[], downloadUrl:'https://wdl1.cache.wps.cn/wps/download/W.P.S.12.8.0.18906.exe', officialSite:'https://www.wps.cn', license:'个人免费/企业付费', language:['简体中文','繁体中文','English'], updateDate:'2026-06-01', downloads:4500000, rating:4.5, tags:['办公','文档','表格','PPT','PDF'] },
  { id:'6', name:'PotPlayer', slug:'potplayer', version:'1.7.22230', size:'32.6 MB', platform:['windows'], category:'media', description:'韩国 Kakao 出品的全能视频播放器，支持几乎所有视频格式，解码能力极强。', longDescription:'PotPlayer 是韩国 Kakao 公司开发的视频播放器，前身是 KMPlayer。支持播放几乎所有音视频格式，内置强大的解码器，无需额外安装解码包。支持硬件加速、3D 视频、字幕同步、画面增强、直播流播放等功能。界面简洁，操作流畅，资源占用低，被众多用户誉为 Windows 上最好的本地视频播放器。', icon:'🎬', screenshots:[], downloadUrl:'https://t1.daumcdn.net/potplayer/PotPlayer/Version/Latest/PotPlayerSetup64.exe', officialSite:'https://potplayer.tv', license:'免费', language:['简体中文','English','한국어'], updateDate:'2026-06-05', downloads:3200000, rating:4.8, tags:['视频播放器','多媒体','解码'] },
  { id:'7', name:'Bandizip', slug:'bandizip', version:'7.36', size:'7.8 MB', platform:['windows','mac'], category:'system', description:'快速轻量的压缩软件，支持智能解压和图片预览，界面优雅。', longDescription:'Bandizip 是一款来自韩国的压缩解压软件，以速度快、界面美观著称。支持 ZIP、7Z、RAR、ISO 等 30 多种格式。智能解压功能可以自动创建文件夹避免文件散落一地。内置图片预览，不解压即可查看压缩包内的图片。支持密码管理和加密压缩。', icon:'🗜️', screenshots:[], downloadUrl:'https://dl.bandisoft.com/bandizip.std/BANDIZIP-SETUP-STD-ALL.EXE', officialSite:'https://www.bandisoft.com/bandizip', license:'免费/专业版付费', language:['简体中文','English','한국어'], updateDate:'2026-06-15', downloads:1800000, rating:4.7, tags:['压缩','解压','文件管理'] },
  { id:'8', name:'Everything', slug:'everything', version:'1.4.1.1026', size:'1.8 MB', platform:['windows'], category:'system', description:'Windows 文件搜索神器，秒级索引全盘文件，输入即搜到。', longDescription:'Everything 是一款极速文件搜索工具，通过直接读取 NTFS 文件系统的 MFT（主文件表）实现毫秒级搜索。与 Windows 自带的搜索不同，Everything 在输入关键词的同时就能显示结果，速度惊人。支持正则表达式、布尔运算、高级筛选等强大搜索功能。', icon:'🔍', screenshots:[], downloadUrl:'https://www.voidtools.com/Everything-1.4.1.1026.x64-Setup.exe', officialSite:'https://www.voidtools.com', license:'免费', language:['简体中文','English'], updateDate:'2026-05-28', downloads:2100000, rating:4.9, tags:['搜索','文件管理','效率工具'] },
  { id:'9', name:'Geek Uninstaller', slug:'geek', version:'1.5.1', size:'6.5 MB', platform:['windows'], category:'system', description:'轻量级软件卸载工具，彻底清除残留文件和注册表项。', longDescription:'Geek Uninstaller 是一款小巧但强大的软件卸载工具。它能够扫描并清除软件卸载后残留的文件、文件夹和注册表项。支持强制卸载顽固软件、查看注册表条目、搜索已安装软件等功能。绿色免安装，仅 6MB，放在 U 盘里随用随开。专业版还支持批量卸载和实时安装监控。', icon:'🗑️', screenshots:[], downloadUrl:'https://geekuninstaller.com/geek.zip', officialSite:'https://geekuninstaller.com', license:'免费/专业版付费', language:['English','简体中文'], updateDate:'2026-06-02', downloads:980000, rating:4.6, tags:['卸载','清理','系统工具'] },
  { id:'10', name:'OBS Studio', slug:'obs', version:'31.0.1', size:'112 MB', platform:['windows','mac','linux'], category:'media', description:'免费开源的录屏和直播软件，主播和视频创作者的首选工具。', longDescription:'OBS Studio 是全球最流行的免费开源录屏和直播推流软件。支持多场景切换、多源混流（摄像头、屏幕、图片、文字、浏览器）、音频混音、滤镜特效、虚拟摄像头等功能。兼容 Twitch、YouTube、Bilibili、抖音等主流直播平台。支持 NVENC、AMD AMF、Intel QuickSync 等硬件编码加速。', icon:'🎥', screenshots:[], downloadUrl:'https://cdn-fastly.obsproject.com/downloads/OBS-Studio-31.0.1-Windows-Installer.exe', officialSite:'https://obsproject.com', license:'免费开源 (GPLv2)', language:['简体中文','English'], updateDate:'2026-06-14', downloads:4200000, rating:4.8, tags:['录屏','直播','视频','开源'] },
  { id:'11', name:'Google Chrome', slug:'chrome', version:'128.0.6613.137', size:'98.5 MB', platform:['windows','mac','android','ios'], category:'network', description:'全球使用率最高的浏览器，速度快、扩展丰富、跨平台同步。', longDescription:'Google Chrome 是目前全球市场份额最高的网页浏览器。采用 Blink 渲染引擎和 V8 JavaScript 引擎，网页加载速度快。支持 Chrome Web Store 海量扩展程序，跨设备同步书签、密码和历史记录。内置安全浏览、恶意网站拦截、自动翻译等功能。', icon:'🌐', screenshots:[], downloadUrl:'https://dl.google.com/chrome/install/ChromeStandaloneSetup64.exe', officialSite:'https://www.google.com/chrome', license:'免费', language:['简体中文','English'], updateDate:'2026-06-13', downloads:9800000, rating:4.6, tags:['浏览器','网络','Google'] },
  { id:'12', name:'Notepad++', slug:'notepadpp', version:'8.7.2', size:'4.8 MB', platform:['windows'], category:'dev', description:'轻量级文本代码编辑器，启动快、语法高亮、插件丰富。', longDescription:'Notepad++ 是 Windows 平台上最受欢迎的文本编辑器之一，基于 Scintilla 编辑组件。支持 80 多种编程语言的语法高亮和代码折叠，支持多标签页、宏录制、正则搜索替换、列编辑模式。通过插件系统可扩展 FTP、代码对比、十六进制编辑等功能。启动速度极快（< 1 秒），适合快速编辑文本和代码。', icon:'📄', screenshots:[], downloadUrl:'https://github.com/notepad-plus-plus/notepad-plus-plus/releases/download/v8.7.2/npp.8.7.2.Installer.x64.exe', officialSite:'https://notepad-plus-plus.org', license:'免费开源 (GPL)', language:['简体中文','English'], updateDate:'2026-06-05', downloads:3500000, rating:4.8, tags:['文本编辑器','代码','开源'] },
  { id:'13', name:'Malwarebytes', slug:'malwarebytes', version:'5.2.2', size:'320 MB', platform:['windows','mac','android'], category:'security', description:'专业恶意软件查杀工具，与现有杀软兼容，清理顽固病毒。', longDescription:'Malwarebytes 是一款专业的恶意软件检测和清除工具。与传统的杀毒软件不同，它专注于查杀病毒、木马、间谍软件、勒索软件、广告软件等恶意程序。可以与其他杀毒软件同时运行而不冲突，适合用于二次扫描和清理顽固感染。免费版支持手动扫描和清除。', icon:'🔒', screenshots:[], downloadUrl:'https://downloads.malwarebytes.com/file/mb5-windows', officialSite:'https://www.malwarebytes.com', license:'免费/高级版付费', language:['English','简体中文'], updateDate:'2026-06-09', downloads:2100000, rating:4.5, tags:['杀毒','安全','恶意软件','清理'] },
  { id:'14', name:'剪映专业版', slug:'jianying', version:'7.2.0', size:'586 MB', platform:['windows','mac'], category:'media', description:'字节跳动出品的免费视频剪辑软件，模板丰富，AI 功能强大。', longDescription:'剪映专业版是字节跳动推出的免费视频剪辑软件。支持多轨道编辑、关键帧动画、调色、美颜、AI 字幕生成、AI 语音转文字、AI 数字人等功能。内置海量素材模板、音效、贴纸、转场效果。导出无水印。支持 4K 视频编辑和导出。适合短视频创作者和入门级视频剪辑用户。', icon:'✂️', screenshots:[], downloadUrl:'https://lf3-package.vlabstatic.com/obj/faceu-packages/Jianying_pro_7_2_0.exe', officialSite:'https://www.capcut.cn', license:'免费', language:['简体中文'], updateDate:'2026-06-14', downloads:5800000, rating:4.7, tags:['视频剪辑','AI','短视频','字幕'] },
  { id:'15', name:'Git', slug:'git', version:'2.47.0', size:'62.3 MB', platform:['windows','mac','linux'], category:'dev', description:'分布式版本控制系统，开发者必备的代码管理工具。', longDescription:'Git 是目前最流行的分布式版本控制系统，由 Linus Torvalds 创建。用于跟踪文件变化、协调多人协作开发。支持分支管理、合并、标签、差异对比、历史回溯等功能。配合 GitHub/GitLab/Gitee 等平台使用，是现代软件开发工作流的基础。Git Bash 提供了类 Unix 的命令行环境。', icon:'🔄', screenshots:[], downloadUrl:'https://github.com/git-for-windows/git/releases/download/v2.47.0.windows.1/Git-2.47.0-64-bit.exe', officialSite:'https://git-scm.com', license:'免费开源 (GPLv2)', language:['English','简体中文'], updateDate:'2026-06-07', downloads:7800000, rating:4.9, tags:['版本控制','Git','开发','开源'] },
  { id:'16', name:'uTorrent', slug:'utorrent', version:'3.6.0', size:'2.8 MB', platform:['windows','mac'], category:'network', description:'经典的轻量级 BT 下载工具，资源占用小，下载速度快。', longDescription:'uTorrent（µTorrent）是最经典的轻量级 BitTorrent 客户端之一，安装包仅 3MB。支持磁力链接、RSS 自动下载、远程控制、定时任务、带宽限制等功能。资源占用极低，后台运行时对系统性能几乎无影响。支持 Windows 和 macOS。注意安装时取消勾选可选软件。', icon:'📥', screenshots:[], downloadUrl:'https://www.utorrent.com/downloads/complete/track/stable/os/win', officialSite:'https://www.utorrent.com', license:'免费/Pro 付费', language:['English','简体中文'], updateDate:'2026-06-01', downloads:4200000, rating:4.3, tags:['BT下载','P2P','磁力链接'] },
  { id:'17', name:'Python', slug:'python', version:'3.13.1', size:'27.8 MB', platform:['windows','mac','linux'], category:'dev', description:'最流行的编程语言之一，简单易学，应用领域广泛。', longDescription:'Python 是一种解释型、面向对象的高级编程语言。语法简洁易读，拥有庞大的标准库和第三方库生态系统。广泛应用于 Web 开发（Django/Flask）、数据科学（Pandas/NumPy）、人工智能（TensorFlow/PyTorch）、自动化脚本、网络爬虫等领域。连续多年位居 TIOBE 编程语言排行榜榜首。', icon:'🐍', screenshots:[], downloadUrl:'https://www.python.org/ftp/python/3.13.1/python-3.13.1-amd64.exe', officialSite:'https://www.python.org', license:'免费开源 (PSF)', language:['English'], updateDate:'2026-06-14', downloads:6500000, rating:4.8, tags:['编程语言','Python','开发','AI'] },
  { id:'18', name:'IDM', slug:'idm', version:'6.42 Build 25', size:'10.5 MB', platform:['windows'], category:'network', description:'Internet Download Manager，最强下载加速工具，支持多线程和浏览器集成。', longDescription:'Internet Download Manager (IDM) 是 Windows 上最流行的下载管理工具。采用动态文件分割和多线程下载技术，可将下载速度提升多达 5 倍。支持断点续传、定时下载、下载队列、站点抓取、浏览器自动捕获下载链接等功能。无缝集成 Chrome、Edge、Firefox 等主流浏览器。', icon:'⚡', screenshots:[], downloadUrl:'https://mirror2.internetdownloadmanager.com/idman642build25.exe', officialSite:'https://www.internetdownloadmanager.com', license:'付费（30天试用）', language:['English','简体中文'], updateDate:'2026-06-02', downloads:3500000, rating:4.7, tags:['下载工具','加速','浏览器集成'] },
];

export function getSoftwareBySlug(slug: string): Software | undefined {
  return SOFTWARE_LIST.find((s) => s.slug === slug);
}

export function getSoftwareByCategory(category: string): Software[] {
  return SOFTWARE_LIST.filter((s) => s.category === category);
}

export function getSoftwareByPlatform(platform: string): Software[] {
  return SOFTWARE_LIST.filter((s) => s.platform.includes(platform as any));
}

export function searchSoftware(query: string): Software[] {
  const q = query.toLowerCase();
  return SOFTWARE_LIST.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.description.toLowerCase().includes(q) ||
      s.tags.some((t) => t.includes(q)) ||
      s.category.includes(q)
  );
}
